# Generated by Django 6.0 on 2025-12-27 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Oluşturma'), ('update', 'Güncelleme'), ('delete', 'Silme'), ('view', 'Görüntüleme'), ('login', 'Giriş'), ('logout', 'Çıkış'), ('upload', 'Yükleme'), ('download', 'İndirme'), ('approve', 'Onaylama'), ('reject', 'Reddetme')], max_length=20, verbose_name='Aksiyon Tipi')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model Adı')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nesne ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Nesne Temsili')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Ekstra Veri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Aktivite Logu',
                'verbose_name_plural': 'Aktivite Logları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('info', 'Bilgi'), ('success', 'Başarılı'), ('warning', 'Uyarı'), ('error', 'Hata'), ('task', 'Görev'), ('order', 'Sipariş'), ('document', 'Belge')], default='info', max_length=20, verbose_name='Bildirim Tipi')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Bağlantı')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
    ]
