# Generated by Django 6.0 on 2025-12-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gid',
            field=models.CharField(blank=True, help_text='Active Directory Global ID', max_length=100, null=True, unique=True, verbose_name='GID'),
        ),
    ]
