# Generated by Django 4.2.3 on 2026-01-04 21:31

from django.db import migrations, models
import re


def generate_codes(apps, schema_editor):
    """Mevcut departmanlar için code oluştur"""
    Department = apps.get_model('accounts', 'Department')
    
    for dept in Department.objects.all():
        code = dept.name.upper()
        # Türkçe karakter dönüşümü
        tr_map = {
            'Ç': 'C', 'Ğ': 'G', 'I': 'I', 'İ': 'I', 'Ö': 'O', 'Ş': 'S', 'Ü': 'U',
            'ç': 'c', 'ğ': 'g', 'ı': 'i', 'i': 'i', 'ö': 'o', 'ş': 's', 'ü': 'u'
        }
        for tr_char, en_char in tr_map.items():
            code = code.replace(tr_char, en_char)
        code = re.sub(r'[^A-Z0-9]', '_', code)
        code = re.sub(r'_+', '_', code).strip('_')[:100]
        
        # Unique olmasını sağla
        base_code = code
        counter = 1
        while Department.objects.filter(code=code).exclude(pk=dept.pk).exists():
            code = f"{base_code}_{counter}"
            counter += 1
        
        dept.code = code
        dept.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_gid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_type',
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, help_text='Otomatik oluşturulur veya manuel girilebilir', max_length=100, verbose_name='Departman Kodu'),
        ),
        migrations.AddField(
            model_name='department',
            name='org_code',
            field=models.CharField(blank=True, help_text="Excel'deki Department (org code) değeri", max_length=100, null=True, verbose_name='Organizasyon Kodu'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Departman Adı'),
        ),
        # Mevcut kayıtlar için code oluştur
        migrations.RunPython(generate_codes, reverse_code=migrations.RunPython.noop),
        # Sonra unique constraint ekle
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, help_text='Otomatik oluşturulur veya manuel girilebilir', max_length=100, unique=True, verbose_name='Departman Kodu'),
        ),
    ]
