# Generated by Django 6.0 on 2025-12-27 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, help_text='Teklif için genel açıklama', verbose_name='Açıklama')),
                ('original_text', models.TextField(help_text='Kullanıcının girdiği orijinal teklif açıklaması', verbose_name='Orijinal Metin')),
                ('generated_content', models.TextField(blank=True, help_text='AI tarafından oluşturulan teklif içeriği', verbose_name='Oluşturulan İçerik')),
                ('equipment_details', models.JSONField(blank=True, default=list, help_text='AI tarafından çıkarılan ekipman bilgileri', verbose_name='Ekipman Detayları')),
                ('equipment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ekipman Değeri')),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Aylık Ödeme')),
                ('lease_term_months', models.PositiveIntegerField(default=36, verbose_name='Kiralama Süresi (Ay)')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Peşinat')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('generating', 'Oluşturuluyor'), ('ready', 'Hazır'), ('sent', 'Gönderildi'), ('viewed', 'Görüntülendi'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('expired', 'Süresi Doldu')], default='draft', max_length=20, verbose_name='Durum')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='proposals/pdfs/', verbose_name='PDF Dosyası')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Tarihi')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Görüntülenme Tarihi')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Yanıt Tarihi')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Geçerlilik Tarihi')),
                ('ai_model_used', models.CharField(blank=True, max_length=100, verbose_name='Kullanılan AI Modeli')),
                ('generation_time', models.FloatField(blank=True, null=True, verbose_name='Oluşturma Süresi (sn)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='customers.customer', verbose_name='Müşteri')),
                ('salesperson', models.ForeignKey(limit_choices_to={'user_type': 'salesperson'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Satış Temsilcisi')),
            ],
            options={
                'verbose_name': 'Teklif',
                'verbose_name_plural': 'Teklifler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Alıcı Email')),
                ('subject', models.CharField(max_length=300, verbose_name='Konu')),
                ('body', models.TextField(verbose_name='İçerik')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='AI Tarafından Oluşturuldu')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Açılma Tarihi')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='proposals.proposal', verbose_name='Teklif')),
            ],
            options={
                'verbose_name': 'Teklif Emaili',
                'verbose_name_plural': 'Teklif Emailleri',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('introduction', 'Giriş'), ('equipment', 'Ekipman Detayları'), ('pricing', 'Fiyatlandırma'), ('terms', 'Şartlar ve Koşullar'), ('timeline', 'Zaman Çizelgesi'), ('benefits', 'Avantajlar'), ('conclusion', 'Sonuç'), ('custom', 'Özel Bölüm')], max_length=20, verbose_name='Bölüm Tipi')),
                ('title', models.CharField(max_length=200, verbose_name='Bölüm Başlığı')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_editable', models.BooleanField(default=True, verbose_name='Düzenlenebilir')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='proposals.proposal', verbose_name='Teklif')),
            ],
            options={
                'verbose_name': 'Teklif Bölümü',
                'verbose_name_plural': 'Teklif Bölümleri',
                'ordering': ['order'],
            },
        ),
    ]
