# Generated by Django 4.2.3 on 2025-12-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Varsayılan Teklif Şablonu', max_length=200, verbose_name='Şablon Adı')),
                ('email_subject', models.CharField(default='Leasing Teklifi - {company_name}', help_text='Kullanılabilir değişkenler: {company_name}, {contact_person}, {equipment_type}', max_length=300, verbose_name='Email Konusu')),
                ('email_body', models.TextField(default='Sayın {contact_person},\n\n{company_name} için hazırladığımız leasing teklifini ekte bulabilirsiniz.\n\nTeklif Özeti:\n- Ekipman: {equipment_description}\n- Kiralama Süresi: {lease_term_months} ay\n- Aylık Ödeme: {monthly_payment} {currency}\n- Toplam Tutar: {total_amount} {currency}\n\nTeklifimizin geçerlilik süresi {valid_days} gündür.\n\nSorularınız için bizimle iletişime geçebilirsiniz.\n\nSaygılarımızla,\n{salesperson_name}\n{salesperson_email}\n{salesperson_phone}', help_text='Kullanılabilir değişkenler: {company_name}, {contact_person}, {equipment_description}, {lease_term_months}, {monthly_payment}, {total_amount}, {currency}, {valid_days}, {salesperson_name}, {salesperson_email}, {salesperson_phone}', verbose_name='Email İçeriği')),
                ('pdf_content', models.TextField(default='<h1>Leasing Teklifi</h1>\n<p><strong>Tarih:</strong> {date}</p>\n<p><strong>Teklif No:</strong> {proposal_number}</p>\n\n<h2>Müşteri Bilgileri</h2>\n<p><strong>Firma:</strong> {company_name}</p>\n<p><strong>İlgili Kişi:</strong> {contact_person}</p>\n<p><strong>Email:</strong> {customer_email}</p>\n\n<h2>Ekipman Detayları</h2>\n<p>{equipment_description}</p>\n\n<h2>Finansal Koşullar</h2>\n<table>\n<tr><td>Ekipman Değeri:</td><td>{equipment_value} {currency}</td></tr>\n<tr><td>Peşinat:</td><td>{down_payment} {currency}</td></tr>\n<tr><td>Kiralama Süresi:</td><td>{lease_term_months} ay</td></tr>\n<tr><td>Aylık Ödeme:</td><td>{monthly_payment} {currency}</td></tr>\n<tr><td>Toplam Tutar:</td><td>{total_amount} {currency}</td></tr>\n</table>\n\n<h2>Genel Koşullar</h2>\n<ul>\n<li>Bu teklif {valid_days} gün geçerlidir.</li>\n<li>Fiyatlara KDV dahil değildir.</li>\n<li>Teslim süresi sözleşme imzasından itibaren belirlenecektir.</li>\n</ul>\n\n<p>Saygılarımızla,</p>\n<p><strong>{salesperson_name}</strong><br>\n{salesperson_email}<br>\n{salesperson_phone}</p>', help_text='HTML formatında teklif içeriği', verbose_name='PDF İçeriği (HTML)')),
                ('default_valid_days', models.PositiveIntegerField(default=30, verbose_name='Varsayılan Geçerlilik Süresi (Gün)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Teklif Şablonu',
                'verbose_name_plural': 'Teklif Şablonları',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='currency',
            field=models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='email_body',
            field=models.TextField(blank=True, verbose_name='Email İçeriği'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='email_subject',
            field=models.CharField(blank=True, max_length=300, verbose_name='Email Konusu'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='pdf_content',
            field=models.TextField(blank=True, help_text='Özelleştirilmiş PDF içeriği', verbose_name='PDF İçeriği'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Toplam Tutar'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('pending_approval', 'Onay Bekliyor'), ('generating', 'Oluşturuluyor'), ('ready', 'Hazır'), ('sent', 'Gönderildi'), ('viewed', 'Görüntülendi'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('expired', 'Süresi Doldu')], default='draft', max_length=20, verbose_name='Durum'),
        ),
    ]
