# Generated by Django 6.0 on 2025-12-28 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_proposaltemplate_proposal_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposaltemplate',
            name='pdf_content',
        ),
        migrations.AddField(
            model_name='proposaltemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Bu şablonun ne amaçla kullanılacağına dair açıklama', verbose_name='Şablon Açıklaması'),
        ),
        migrations.AddField(
            model_name='proposaltemplate',
            name='input_guide',
            field=models.TextField(default='Teklif oluşturmak için aşağıdaki bilgileri içeren bir açıklama yazın:\n\n• Ekipman türü ve markası (örn: Caterpillar ekskavatör, Komatsu dozer)\n• Ekipman adedi\n• Tahmini ekipman değeri\n• İstenen kiralama süresi (ay)\n• Peşinat tercihi varsa\n• Özel istekler veya notlar\n\nÖrnek:\n"ABC İnşaat için 2 adet Caterpillar 320 ekskavatör ve 1 adet Komatsu D65 dozer teklifi hazırla. Toplam değer yaklaşık 5 milyon TL, 36 ay vade istiyorlar. %10 peşinat ödeyebilirler, aylık taksitleri mümkün olduğunca düşük tutmak istiyorlar. Firma inşaat sektöründe 10 yıldır faaliyet gösteriyor."', help_text='Kullanıcıya teklif oluşturmak için ne yazması gerektiğini gösteren örnek metin', verbose_name='Giriş Rehberi'),
        ),
        migrations.CreateModel(
            name='TemplateSectionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('introduction', 'Giriş'), ('equipment_details', 'Ekipman Detayları'), ('pricing', 'Fiyatlandırma'), ('terms', 'Şartlar ve Koşullar'), ('benefits', 'Avantajlar'), ('timeline', 'Zaman Çizelgesi'), ('conclusion', 'Sonuç'), ('custom', 'Özel Bölüm')], default='custom', max_length=30, verbose_name='Alan Tipi')),
                ('title', models.CharField(help_text='Bu bölümün başlığı (örn: "Giriş", "Ekipman Detayları")', max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(default='Bu bölümü profesyonel ve ikna edici bir dille doldurun.', help_text="AI'a bu alanı nasıl doldurması gerektiğini anlatan talimat", verbose_name='Alan Açıklaması')),
                ('placeholder_content', models.TextField(blank=True, help_text='Bu alanda ne tür içerik olacağına dair örnek', verbose_name='Örnek İçerik')),
                ('is_ai_generated', models.BooleanField(default=True, help_text='Bu alan AI tarafından mı doldurulacak yoksa sabit mi kalacak', verbose_name='AI Tarafından Oluşturulacak')),
                ('static_content', models.TextField(blank=True, help_text='AI oluşturmayacaksa kullanılacak sabit içerik', verbose_name='Sabit İçerik')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_required', models.BooleanField(default=True, help_text='Bu bölüm teklifte mutlaka bulunmalı mı', verbose_name='Zorunlu')),
                ('include_in_pdf', models.BooleanField(default=True, verbose_name="PDF'e Dahil Et")),
                ('include_in_email', models.BooleanField(default=False, verbose_name="Email'e Dahil Et")),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='proposals.proposaltemplate', verbose_name='Şablon')),
            ],
            options={
                'verbose_name': 'Şablon Bölümü',
                'verbose_name_plural': 'Şablon Bölümleri',
                'ordering': ['order'],
            },
        ),
    ]
