# Generated by Django 6.0 on 2025-12-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_remove_proposaltemplate_pdf_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Müşterinin red sebebi', verbose_name='Red Sebebi'),
        ),
    ]
