# Generated by Django 6.0 on 2025-12-27 15:30

import django.core.validators
import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Şablon Adı')),
                ('document_type', models.CharField(choices=[('kvkk', 'KVKK Onay Formu'), ('id_card', 'Kimlik Fotokopisi'), ('tax_cert', 'Vergi Levhası'), ('signature', 'İmza Sirküleri'), ('trade_reg', 'Ticaret Sicil Gazetesi'), ('financial', 'Mali Tablolar'), ('invoice', 'Fatura'), ('contract', 'Sözleşme'), ('proposal', 'Teklif'), ('other', 'Diğer')], max_length=20, verbose_name='Belge Tipi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_required', models.BooleanField(default=True, verbose_name='Zorunlu')),
                ('allowed_extensions', models.CharField(default='pdf,doc,docx,jpg,jpeg,png', help_text='Virgülle ayrılmış uzantılar', max_length=100, verbose_name='İzin Verilen Uzantılar')),
                ('max_file_size_mb', models.PositiveIntegerField(default=10, verbose_name='Maksimum Dosya Boyutu (MB)')),
                ('sample_file', models.FileField(blank=True, null=True, upload_to='document_templates/', verbose_name='Örnek Dosya')),
                ('instructions', models.TextField(blank=True, verbose_name='Yükleme Talimatları')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Belge Şablonu',
                'verbose_name_plural': 'Belge Şablonları',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KVKKDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_sent', models.BooleanField(default=False, verbose_name='Form Gönderildi')),
                ('form_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Form Gönderilme Tarihi')),
                ('signed_document', models.FileField(blank=True, null=True, upload_to='kvkk_documents/', verbose_name='İmzalı Belge')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='İmza Tarihi')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Onaylandı')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('salesperson_comment', models.TextField(blank=True, help_text='Müşterinin göreceği yorum', verbose_name='Satışçı Yorumu')),
                ('internal_notes', models.TextField(blank=True, help_text='Sadece personelin göreceği notlar', verbose_name='İç Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kvkk_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kvkk_document', to='customers.customer', verbose_name='Müşteri')),
                ('form_sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kvkk_forms_sent', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'KVKK Belgesi',
                'verbose_name_plural': 'KVKK Belgeleri',
            },
        ),
        migrations.CreateModel(
            name='KVKKComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Yorum')),
                ('is_internal', models.BooleanField(default=False, help_text='İç yorumlar müşteri tarafından görülmez', verbose_name='İç Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kvkk_comments', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('kvkk_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.kvkkdocument', verbose_name='KVKK Belgesi')),
            ],
            options={
                'verbose_name': 'KVKK Yorumu',
                'verbose_name_plural': 'KVKK Yorumları',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('kvkk', 'KVKK Onay Formu'), ('id_card', 'Kimlik Fotokopisi'), ('tax_cert', 'Vergi Levhası'), ('signature', 'İmza Sirküleri'), ('trade_reg', 'Ticaret Sicil Gazetesi'), ('financial', 'Mali Tablolar'), ('invoice', 'Fatura'), ('contract', 'Sözleşme'), ('proposal', 'Teklif'), ('other', 'Diğer')], max_length=20, verbose_name='Belge Tipi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif', 'xls', 'xlsx'])], verbose_name='Dosya')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Orijinal Dosya Adı')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Dosya Boyutu (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME Tipi')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('uploaded', 'Yüklendi'), ('reviewing', 'İnceleniyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('expired', 'Süresi Doldu')], default='uploaded', max_length=20, verbose_name='Durum')),
                ('ai_validated', models.BooleanField(default=False, verbose_name='AI Doğrulandı')),
                ('ai_validation_score', models.FloatField(blank=True, null=True, verbose_name='AI Doğrulama Skoru')),
                ('ai_validation_notes', models.TextField(blank=True, verbose_name='AI Doğrulama Notları')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Red Sebebi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İnceleme Tarihi')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Son Geçerlilik Tarihi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Yüklenen Belge',
                'verbose_name_plural': 'Yüklenen Belgeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
