# Generated by Django 6.0 on 2025-12-27 19:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvkkdocument',
            name='form_sent',
        ),
        migrations.RemoveField(
            model_name='kvkkdocument',
            name='form_sent_at',
        ),
        migrations.RemoveField(
            model_name='kvkkdocument',
            name='form_sent_by',
        ),
        migrations.RemoveField(
            model_name='kvkkdocument',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='kvkkdocument',
            name='salesperson_comment',
        ),
        migrations.RemoveField(
            model_name='kvkkdocument',
            name='signed_at',
        ),
        migrations.AddField(
            model_name='kvkkdocument',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kvkk_documents_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Satışçı'),
        ),
        migrations.AddField(
            model_name='kvkkdocument',
            name='kvkk_content',
            field=models.TextField(default='', help_text='Bu müşteri için özelleştirilmiş KVKK metni', verbose_name='KVKK Metni'),
        ),
        migrations.AddField(
            model_name='kvkkdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İnceleme Tarihi'),
        ),
        migrations.AddField(
            model_name='kvkkdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kvkk_documents_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen'),
        ),
        migrations.AddField(
            model_name='kvkkdocument',
            name='revision_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Revizyon Sayısı'),
        ),
        migrations.AddField(
            model_name='kvkkdocument',
            name='revision_reason',
            field=models.TextField(blank=True, verbose_name='Revizyon Sebebi'),
        ),
        migrations.AddField(
            model_name='kvkkdocument',
            name='salesperson_notes',
            field=models.TextField(blank=True, help_text='Müşterinin göreceği not', verbose_name='Satışçı Notu'),
        ),
        migrations.AddField(
            model_name='kvkkdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('pending_signature', 'İmza Bekliyor'), ('uploaded', 'Yüklendi'), ('pending_approval', 'Onay Bekliyor'), ('revision_requested', 'Revize İstendi'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='draft', max_length=30, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='kvkkdocument',
            name='template_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='Şablon Versiyonu'),
        ),
        migrations.AddField(
            model_name='kvkkdocument',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yüklenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='kvkkdocument',
            name='signed_document',
            field=models.FileField(blank=True, null=True, upload_to='kvkk_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='İmzalı Belge'),
        ),
        migrations.CreateModel(
            name='KVKKTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Varsayılan KVKK Metni', max_length=255, verbose_name='Şablon Adı')),
                ('content', models.TextField(help_text='HTML formatında KVKK aydınlatma metni', verbose_name='KVKK Metni')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versiyon')),
                ('is_active', models.BooleanField(default=True, help_text='Yeni müşteriler için kullanılacak şablon', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kvkk_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'KVKK Şablonu',
                'verbose_name_plural': 'KVKK Şablonları',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
