# Generated by Django 6.0 on 2025-12-27 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Şirket Adı')),
                ('contact_person', models.CharField(max_length=255, verbose_name='İlgili Kişi')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('secondary_phone', models.CharField(blank=True, max_length=20, verbose_name='İkinci Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('tax_number', models.CharField(blank=True, max_length=20, verbose_name='Vergi Numarası')),
                ('tax_office', models.CharField(blank=True, max_length=100, verbose_name='Vergi Dairesi')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='Sektör')),
                ('company_size', models.CharField(blank=True, help_text='Örn: 1-10, 11-50, 51-200, 200+', max_length=50, verbose_name='Şirket Büyüklüğü')),
                ('stage', models.CharField(choices=[('lead', 'Potansiyel'), ('contacted', 'İletişime Geçildi'), ('qualified', 'Değerlendirildi'), ('proposal_sent', 'Teklif Gönderildi'), ('negotiation', 'Müzakere'), ('contract', 'Sözleşme Aşaması'), ('won', 'Kazanıldı'), ('lost', 'Kaybedildi')], default='lead', max_length=20, verbose_name='Aşama')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], default='medium', max_length=20, verbose_name='Öncelik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tahmini Değer')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('last_contact_date', models.DateTimeField(blank=True, null=True, verbose_name='Son İletişim Tarihi')),
                ('next_followup_date', models.DateField(blank=True, null=True, verbose_name='Sonraki Takip Tarihi')),
                ('salesperson', models.ForeignKey(limit_choices_to={'user_type': 'salesperson'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Satış Temsilcisi')),
                ('user_account', models.OneToOneField(blank=True, help_text='Müşteri portal girişi için', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Hesabı')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('call', 'Telefon Görüşmesi'), ('meeting', 'Toplantı'), ('email', 'Email'), ('note', 'Not'), ('task', 'Görev'), ('status_change', 'Durum Değişikliği')], default='note', max_length=20, verbose_name='Not Tipi')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_notes_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notes', to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Müşteri Notu',
                'verbose_name_plural': 'Müşteri Notları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['stage'], name='customers_c_stage_c28417_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['salesperson'], name='customers_c_salespe_885121_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='customers_c_created_1ed0f4_idx'),
        ),
    ]
