# Generated by Django 6.0 on 2025-12-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Şirket Adı')),
                ('tax_number', models.CharField(blank=True, max_length=20, verbose_name='Vergi Numarası')),
                ('tax_office', models.CharField(blank=True, max_length=100, verbose_name='Vergi Dairesi')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='Sektör')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('company_size', models.CharField(blank=True, help_text='Örn: 1-10, 11-50, 51-200, 200+', max_length=50, verbose_name='Şirket Büyüklüğü')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Şirket',
                'verbose_name_plural': 'Şirketler',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Şirket Adı'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.company', verbose_name='Şirket'),
        ),
    ]
