# Generated by Django 6.0 on 2025-12-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_company_alter_customer_company_name_customer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='kvkk_approved',
            field=models.BooleanField(default=False, help_text='Müşteri KVKK metnini onayladı mı?', verbose_name='KVKK Onaylandı'),
        ),
        migrations.AddField(
            model_name='customer',
            name='kvkk_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='KVKK Onay Tarihi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='kvkk_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='KVKK onayı yapılan IP adresi', null=True, verbose_name='KVKK Onay IP'),
        ),
    ]
