# Generated by Django 4.2.3 on 2025-12-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_kvkk_approved_customer_kvkk_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customernote',
            name='note_type',
            field=models.CharField(choices=[('call', 'Telefon Görüşmesi'), ('meeting', 'Toplantı'), ('email', 'Email'), ('note', 'Not'), ('task', 'Görev'), ('status_change', 'Durum Değişikliği'), ('customer_request', 'Müşteri İsteği')], default='note', max_length=20, verbose_name='Not Tipi'),
        ),
    ]
