# Generated by Django 6.0 on 2025-12-27 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('task_type', models.CharField(choices=[('followup', 'Takip'), ('proposal', 'Teklif Hazırla'), ('document_review', 'Belge İncele'), ('call', 'Telefon Görüşmesi'), ('meeting', 'Toplantı'), ('approval', 'Onay Bekliyor'), ('contract', 'Sözleşme'), ('other', 'Diğer')], default='followup', max_length=20, verbose_name='Görev Tipi')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('in_progress', 'Devam Ediyor'), ('waiting_response', 'Cevap Bekleniyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('manual_priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='medium', max_length=20, verbose_name='Manuel Öncelik')),
                ('ai_priority_score', models.IntegerField(default=50, help_text='0-100 arası, AI tarafından hesaplanır', verbose_name='AI Öncelik Skoru')),
                ('ai_priority_reasoning', models.TextField(blank=True, help_text='AI neden bu skoru verdiğini açıklar', verbose_name='AI Öncelik Açıklaması')),
                ('ai_priority_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='AI Skoru Güncellenme Tarihi')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Son Tarih')),
                ('reminder_date', models.DateTimeField(blank=True, null=True, verbose_name='Hatırlatma Tarihi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kişi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
                'ordering': ['-ai_priority_score', 'due_date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'), models.Index(fields=['assigned_to'], name='tasks_task_assigne_ab55af_idx'), models.Index(fields=['due_date'], name='tasks_task_due_dat_bce847_idx'), models.Index(fields=['ai_priority_score'], name='tasks_task_ai_prio_4ee7b0_idx')],
            },
        ),
    ]
