# Generated by Django 6.0 on 2025-12-27 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('document_validation', 'Belge Validasyonu'), ('task_prioritization', 'Görev Önceliklendirme'), ('proposal_generation', 'Teklif Oluşturma'), ('customer_research', 'Müşteri Araştırması'), ('signature_detection', 'İmza Tespiti'), ('form_validation', 'Form Validasyonu'), ('asset_analysis', 'Varlık Analizi')], max_length=30, verbose_name='Servis Tipi')),
                ('model_name', models.CharField(default='claude-sonnet-4-20250514', max_length=100, verbose_name='Model Adı')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='Prompt Token Sayısı')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='Tamamlama Token Sayısı')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='Toplam Token Sayısı')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('success', 'Başarılı'), ('failed', 'Başarısız'), ('timeout', 'Zaman Aşımı')], default='pending', max_length=20, verbose_name='Durum')),
                ('response_time_ms', models.PositiveIntegerField(default=0, verbose_name='Yanıt Süresi (ms)')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('request_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='İstek Hash')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Ekstra Veri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'AI İstek Logu',
                'verbose_name_plural': 'AI İstek Logları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.PositiveIntegerField(db_index=True, verbose_name='Belge ID')),
                ('document_type', models.CharField(max_length=100, verbose_name='Belge Tipi')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Geçerli')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Güven Skoru')),
                ('validation_details', models.JSONField(default=dict, verbose_name='Validasyon Detayları')),
                ('missing_fields', models.JSONField(default=list, verbose_name='Eksik Alanlar')),
                ('invalid_fields', models.JSONField(default=list, verbose_name='Geçersiz Alanlar')),
                ('warnings', models.JSONField(default=list, verbose_name='Uyarılar')),
                ('ai_reasoning', models.TextField(blank=True, verbose_name='AI Açıklaması')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('request_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_results', to='ai_services.airequestlog', verbose_name='İstek Logu')),
            ],
            options={
                'verbose_name': 'AI Validasyon Sonucu',
                'verbose_name_plural': 'AI Validasyon Sonuçları',
                'ordering': ['-created_at'],
            },
        ),
    ]
