# Generated by Django 6.0 on 2025-12-27 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Sipariş Numarası')),
                ('equipment_type', models.CharField(choices=[('vehicle', 'Araç'), ('machinery', 'İş Makinesi'), ('computer', 'Bilgisayar/IT'), ('office', 'Ofis Ekipmanı'), ('medical', 'Medikal Cihaz'), ('construction', 'İnşaat Ekipmanı'), ('agricultural', 'Tarım Ekipmanı'), ('other', 'Diğer')], max_length=20, verbose_name='Ekipman Türü')),
                ('equipment_brand', models.CharField(blank=True, max_length=100, verbose_name='Marka')),
                ('equipment_model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('equipment_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yıl')),
                ('equipment_description', models.TextField(blank=True, verbose_name='Ekipman Açıklaması')),
                ('equipment_quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('lease_type', models.CharField(choices=[('financial', 'Finansal Kiralama'), ('operational', 'Operasyonel Kiralama'), ('leaseback', 'Sat-Geri Kirala')], default='financial', max_length=20, verbose_name='Kiralama Türü')),
                ('lease_term_months', models.PositiveIntegerField(default=36, verbose_name='Kiralama Süresi (Ay)')),
                ('equipment_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ekipman Değeri')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Peşinat')),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Aylık Ödeme')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Toplam Tutar')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('pending_docs', 'Belge Bekleniyor'), ('docs_review', 'Belgeler İnceleniyor'), ('pending_approval', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('processing', 'İşleniyor'), ('ready', 'Teslime Hazır'), ('delivered', 'Teslim Edildi'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('rejected', 'Reddedildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('requested_delivery_date', models.DateField(blank=True, null=True, verbose_name='İstenen Teslim Tarihi')),
                ('estimated_delivery_date', models.DateField(blank=True, null=True, verbose_name='Tahmini Teslim Tarihi')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='Gerçek Teslim Tarihi')),
                ('lease_start_date', models.DateField(blank=True, null=True, verbose_name='Kiralama Başlangıç Tarihi')),
                ('lease_end_date', models.DateField(blank=True, null=True, verbose_name='Kiralama Bitiş Tarihi')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Müşteri Notları')),
                ('internal_notes', models.TextField(blank=True, verbose_name='İç Notlar')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Red Sebebi')),
                ('wizard_step', models.PositiveIntegerField(default=1, verbose_name='Wizard Adımı')),
                ('wizard_completed', models.BooleanField(default=False, verbose_name='Wizard Tamamlandı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Tarihi')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer', verbose_name='Müşteri')),
                ('salesperson', models.ForeignKey(limit_choices_to={'user_type': 'salesperson'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_orders', to=settings.AUTH_USER_MODEL, verbose_name='Satış Temsilcisi')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('note', 'Not'), ('status', 'Durum Değişikliği'), ('document', 'Belge'), ('system', 'Sistem'), ('customer', 'Müşteri Mesajı')], default='note', max_length=20, verbose_name='Not Tipi')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('is_internal', models.BooleanField(default=False, help_text='İç notlar müşteri tarafından görülmez', verbose_name='İç Not')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Sabitlenmiş')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_notes', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='orders.order', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Sipariş Notu',
                'verbose_name_plural': 'Sipariş Notları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_satisfied', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='orders.order', verbose_name='Sipariş')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requirements', to='documents.documenttemplate', verbose_name='Belge Şablonu')),
                ('uploaded_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement', to='documents.uploadeddocument', verbose_name='Yüklenen Belge')),
            ],
            options={
                'verbose_name': 'Gerekli Belge',
                'verbose_name_plural': 'Gerekli Belgeler',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='orders_orde_custome_c9b64a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['salesperson', 'status'], name='orders_orde_salespe_74748a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requireddocument',
            unique_together={('order', 'template')},
        ),
    ]
