# Generated by Django 6.0 on 2025-12-30 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ADLogEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Şablon Adı')),
                ('subject', models.CharField(max_length=255, verbose_name='Konu')),
                ('body', models.TextField(help_text='Kullanılabilir değişkenler: {analysis_name}, {date}, {total_gids}, {unique_gids}, {discrepancy_count}', verbose_name='İçerik')),
                ('default_to', models.TextField(blank=True, null=True, verbose_name='Varsayılan Alıcılar (TO)')),
                ('default_cc', models.TextField(blank=True, null=True, verbose_name='Varsayılan CC')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan Şablon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Email Şablonu',
                'verbose_name_plural': 'Email Şablonları',
            },
        ),
        migrations.CreateModel(
            name='SystemGID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=100, unique=True, verbose_name='GID')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Görünen Ad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Departman')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Sistem GID',
                'verbose_name_plural': "Sistem GID'leri",
                'ordering': ['gid'],
            },
        ),
        migrations.CreateModel(
            name='ADLogAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Analiz Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('source_path', models.CharField(help_text='Excel dosyalarının okunacağı klasör yolu', max_length=500, verbose_name='Kaynak Dosya Yolu')),
                ('user_checklist_file', models.FileField(blank=True, null=True, upload_to='ad_logs/checklists/', verbose_name='Kullanıcı Kontrol Listesi')),
                ('unique_gids_file', models.FileField(blank=True, null=True, upload_to='ad_logs/gids/', verbose_name='Unique GID Listesi')),
                ('log_file', models.FileField(blank=True, null=True, upload_to='ad_logs/logs/', verbose_name='Farklılık Log Dosyası')),
                ('processed_files_count', models.IntegerField(default=0, verbose_name='İşlenen Dosya Sayısı')),
                ('total_gids_found', models.IntegerField(default=0, verbose_name='Bulunan Toplam GID')),
                ('unique_gids_count', models.IntegerField(default=0, verbose_name='Unique GID Sayısı')),
                ('discrepancy_count', models.IntegerField(default=0, verbose_name='Farklılık Sayısı')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('email_pending', 'Email Onayı Bekliyor'), ('email_sent', 'Email Gönderildi'), ('failed', 'Hatalı')], default='pending', max_length=20, verbose_name='Durum')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Hata Mesajı')),
                ('email_to', models.TextField(blank=True, help_text='Virgülle ayrılmış email adresleri', null=True, verbose_name='Email Alıcıları (TO)')),
                ('email_cc', models.TextField(blank=True, help_text='Virgülle ayrılmış email adresleri', null=True, verbose_name='Email CC')),
                ('email_subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Konusu')),
                ('email_body', models.TextField(blank=True, null=True, verbose_name='Email İçeriği')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email Gönderim Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'AD Log Analizi',
                'verbose_name_plural': 'AD Log Analizleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GIDDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=100, verbose_name='GID')),
                ('discrepancy_type', models.CharField(choices=[('missing_in_system', 'Sistemde Yok'), ('missing_in_ad', "AD'de Yok"), ('data_mismatch', 'Veri Uyuşmazlığı')], max_length=30, verbose_name='Farklılık Tipi')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detaylar')),
                ('source_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kaynak Dosya')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='it_tools.adloganalysis', verbose_name='Analiz')),
            ],
            options={
                'verbose_name': 'GID Farklılığı',
                'verbose_name_plural': 'GID Farklılıkları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedADFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Orijinal Dosya Adı')),
                ('file', models.FileField(upload_to='ad_logs/processed/', verbose_name='Dosya')),
                ('gids_count', models.IntegerField(default=0, verbose_name='GID Sayısı')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='İşlenme Zamanı')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_files', to='it_tools.adloganalysis', verbose_name='Analiz')),
            ],
            options={
                'verbose_name': 'İşlenmiş AD Dosyası',
                'verbose_name_plural': 'İşlenmiş AD Dosyaları',
                'ordering': ['-processed_at'],
            },
        ),
    ]
