# Generated by Django 4.2.3 on 2025-12-30 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADLogSourcePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bu path için açıklayıcı bir isim', max_length=255, verbose_name='Tanım Adı')),
                ('source_path', models.CharField(help_text='Excel dosyalarının bulunduğu fileserver yolu', max_length=500, verbose_name='Kaynak Path (Fileserver)')),
                ('output_path', models.CharField(help_text='Sonuç dosyalarının kaydedileceği yerel klasör', max_length=500, verbose_name='Çıktı Path')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'AD Log Kaynak Path',
                'verbose_name_plural': "AD Log Kaynak Path'leri",
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='adloganalysis',
            name='month',
            field=models.IntegerField(choices=[(1, 'Ocak'), (2, 'Şubat'), (3, 'Mart'), (4, 'Nisan'), (5, 'Mayıs'), (6, 'Haziran'), (7, 'Temmuz'), (8, 'Ağustos'), (9, 'Eylül'), (10, 'Ekim'), (11, 'Kasım'), (12, 'Aralık')], default=11, verbose_name='Ay'),
        ),
        migrations.AddField(
            model_name='adloganalysis',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Yıl'),
        ),
        migrations.AlterField(
            model_name='adloganalysis',
            name='source_path',
            field=models.CharField(blank=True, help_text='Excel dosyalarının okunacağı klasör yolu', max_length=500, null=True, verbose_name='Kaynak Dosya Yolu'),
        ),
        migrations.AlterField(
            model_name='adloganalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('downloading', 'Dosyalar İndiriliyor'), ('processing', 'İşleniyor'), ('comparing', 'Karşılaştırılıyor'), ('completed', 'Tamamlandı'), ('email_pending', 'Email Onayı Bekliyor'), ('email_sent', 'Email Gönderildi'), ('failed', 'Hatalı')], default='pending', max_length=20, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='adloganalysis',
            name='source_path_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='it_tools.adlogsourcepath', verbose_name='Kaynak Path Tanımı'),
        ),
    ]
