# Generated by Django 4.2.3 on 2025-12-30 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_tools', '0002_adlogsourcepath_adloganalysis_month_and_more'),
    ]

    operations = [
        # Tabloyu yeniden adlandır
        migrations.RenameModel(
            old_name='ADLogSourcePath',
            new_name='PathDefinition',
        ),
        # usage_type field ekle
        migrations.AddField(
            model_name='pathdefinition',
            name='usage_type',
            field=models.CharField(
                choices=[
                    ('AD_LOG', 'AD Log Analizi'),
                    ('EMAIL_TEMPLATE', 'Email Şablonları'),
                    ('BACKUP', 'Yedekleme'),
                    ('EXPORT', 'Veri Dışa Aktarma'),
                    ('OTHER', 'Diğer'),
                ],
                default='AD_LOG',
                help_text='Bu path hangi işlem için kullanılacak',
                max_length=50,
                verbose_name='Kullanım Türü'
            ),
        ),
        # Meta ayarlarını güncelle
        migrations.AlterModelOptions(
            name='pathdefinition',
            options={
                'ordering': ['usage_type', '-is_default', 'name'],
                'verbose_name': 'Path Tanımı',
                'verbose_name_plural': 'Path Tanımları'
            },
        ),
        # unique_together ekle
        migrations.AlterUniqueTogether(
            name='pathdefinition',
            unique_together={('usage_type', 'name')},
        ),
        # is_default field help_text güncelle
        migrations.AlterField(
            model_name='pathdefinition',
            name='is_default',
            field=models.BooleanField(
                default=False,
                help_text='Bu tip için varsayılan path',
                verbose_name='Varsayılan'
            ),
        ),
    ]
