# Generated by Django 4.2.3 on 2025-12-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_tools', '0003_rename_to_pathdefinition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adlogemailtemplate',
            options={'ordering': ['usage_type', '-is_default', 'name'], 'verbose_name': 'Email Şablonu', 'verbose_name_plural': 'Email Şablonları'},
        ),
        migrations.AddField(
            model_name='adlogemailtemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='adlogemailtemplate',
            name='usage_type',
            field=models.CharField(choices=[('AD_LOG', 'AD Log Analizi'), ('SYSTEM_NOTIFICATION', 'Sistem Bildirimi'), ('REPORT', 'Rapor Gönderimi'), ('ALERT', 'Uyarı'), ('OTHER', 'Diğer')], default='AD_LOG', help_text='Bu şablon hangi işlem için kullanılacak', max_length=50, verbose_name='Kullanım Türü'),
        ),
        migrations.AlterField(
            model_name='adlogemailtemplate',
            name='body',
            field=models.TextField(help_text='Kullanılabilir: {{analysis_name}}, {{period}}, {{date}}, {{total_gids}}, {{unique_gids}}, {{discrepancy_count}}, {{unmatched_gids}}', verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='adlogemailtemplate',
            name='default_cc',
            field=models.TextField(blank=True, help_text='Virgülle ayrılmış email adresleri', null=True, verbose_name='Varsayılan CC'),
        ),
        migrations.AlterField(
            model_name='adlogemailtemplate',
            name='default_to',
            field=models.TextField(blank=True, help_text='Virgülle ayrılmış email adresleri', null=True, verbose_name='Varsayılan Alıcılar (TO)'),
        ),
        migrations.AlterField(
            model_name='adlogemailtemplate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Bu tip için varsayılan şablon', verbose_name='Varsayılan Şablon'),
        ),
        migrations.AlterField(
            model_name='adlogemailtemplate',
            name='subject',
            field=models.CharField(help_text='Kullanılabilir: {{analysis_name}}, {{period}}, {{date}}', max_length=255, verbose_name='Konu'),
        ),
        migrations.AlterField(
            model_name='pathdefinition',
            name='output_path',
            field=models.CharField(help_text='Sonuç dosyalarının kaydedileceği hedef klasör', max_length=500, verbose_name='Çıktı Path'),
        ),
        migrations.AlterField(
            model_name='pathdefinition',
            name='source_path',
            field=models.CharField(help_text='Dosyaların okunacağı kaynak yol', max_length=500, verbose_name='Kaynak Path (Fileserver)'),
        ),
        migrations.AlterUniqueTogether(
            name='adlogemailtemplate',
            unique_together={('usage_type', 'name')},
        ),
    ]
