# Generated by Django 4.2.3 on 2026-01-04 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('it_tools', '0005_usagetype_model_and_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adloganalysis',
            name='month',
            field=models.IntegerField(choices=[(1, 'Ocak'), (2, 'Şubat'), (3, 'Mart'), (4, 'Nisan'), (5, 'Mayıs'), (6, 'Haziran'), (7, 'Temmuz'), (8, 'Ağustos'), (9, 'Eylül'), (10, 'Ekim'), (11, 'Kasım'), (12, 'Aralık')], default=12, verbose_name='Ay'),
        ),
        migrations.AlterField(
            model_name='adloganalysis',
            name='year',
            field=models.IntegerField(default=2026, verbose_name='Yıl'),
        ),
        migrations.CreateModel(
            name='BulkUserImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Import Adı')),
                ('excel_file', models.FileField(upload_to='bulk_imports/users/', verbose_name='Excel Dosyası')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('completed_with_errors', 'Hatalarla Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=30, verbose_name='Durum')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Toplam Satır')),
                ('created_count', models.IntegerField(default=0, verbose_name='Oluşturulan')),
                ('updated_count', models.IntegerField(default=0, verbose_name='Güncellenen')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='Atlanan')),
                ('error_count', models.IntegerField(default=0, verbose_name='Hatalı')),
                ('log', models.TextField(blank=True, null=True, verbose_name='İşlem Logu')),
                ('error_details', models.TextField(blank=True, null=True, verbose_name='Hata Detayları')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_user_imports', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Toplu Kullanıcı Import',
                'verbose_name_plural': "Toplu Kullanıcı Import'ları",
                'ordering': ['-created_at'],
            },
        ),
    ]
